// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: PuiLexer.flex

// Copyright 2000-2022 JetBrains s.r.o. and other contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package online.generalpashon.jpizeuihighlighter.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;


class PuiLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int WAITING_COMPONENT = 2;
  public static final int WAITING_OPEN_BRACKET = 4;
  public static final int WAITING_CLOSE_BRACKET = 6;
  public static final int WAITING_VALUE = 8;
  public static final int COMPONENT = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\10\u3000\31\u1f00\1\u0100\1\u3100\1\u3200"+
    "\1\u0100\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u3b00\1\u0100\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u4200\1\u1f00\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00"+
    "\1\u4f00\1\u5000\1\u5100\1\u1f00\3\u0100\1\u5200\1\u5300\1\u5400"+
    "\12\u1f00\4\u0100\1\u5500\17\u1f00\2\u0100\1\u5600\41\u1f00\2\u0100"+
    "\1\u5700\1\u5800\2\u1f00\1\u5900\1\u5a00\27\u0100\1\u5b00\2\u0100"+
    "\1\u5c00\45\u1f00\1\u0100\1\u5d00\1\u5e00\11\u1f00\1\u5f00\24\u1f00"+
    "\1\u6000\1\u6100\1\u1f00\1\u6200\1\u6300\1\u6400\1\u6500\2\u1f00"+
    "\1\u6600\5\u1f00\1\u6700\1\u6800\1\u6900\5\u1f00\1\u6a00\1\u6b00"+
    "\4\u1f00\1\u6c00\2\u1f00\1\u6d00\16\u1f00\246\u0100\1\u6e00\20\u0100"+
    "\1\u6f00\1\u7000\25\u0100\1\u7100\34\u0100\1\u7200\14\u1f00\2\u0100"+
    "\1\u7300\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\1\7\2\0\1\10\1\11\1\12\1\0"+
    "\1\13\1\14\1\13\1\15\1\0\12\16\1\17\2\0"+
    "\1\20\2\0\1\21\4\22\1\23\25\22\1\0\1\24"+
    "\2\0\1\25\1\0\1\26\1\22\1\27\1\22\1\30"+
    "\2\22\1\31\4\22\1\32\1\33\1\34\1\35\1\22"+
    "\1\36\1\22\1\37\1\40\1\22\1\41\1\42\1\22"+
    "\1\43\1\44\1\0\1\45\7\0\1\3\32\0\1\1"+
    "\11\0\1\22\12\0\1\22\4\0\1\22\5\0\27\22"+
    "\1\0\37\22\1\0\u01ca\22\4\0\14\22\16\0\5\22"+
    "\7\0\1\22\1\0\1\22\21\0\165\22\1\0\2\22"+
    "\2\0\4\22\1\0\1\22\6\0\1\22\1\0\3\22"+
    "\1\0\1\22\1\0\24\22\1\0\123\22\1\0\213\22"+
    "\1\0\255\22\1\0\46\22\2\0\1\22\6\0\51\22"+
    "\10\0\55\22\1\0\1\22\1\0\2\22\1\0\2\22"+
    "\1\0\1\22\10\0\33\22\4\0\4\22\35\0\13\22"+
    "\5\0\112\22\4\0\146\22\1\0\10\22\2\0\12\22"+
    "\1\0\23\22\2\0\1\22\20\0\73\22\2\0\145\22"+
    "\16\0\66\22\4\0\1\22\2\0\1\22\2\0\56\22"+
    "\22\0\34\22\4\0\13\22\65\0\25\22\1\0\10\22"+
    "\25\0\17\22\1\0\201\22\2\0\12\22\1\0\23\22"+
    "\1\0\10\22\2\0\2\22\2\0\26\22\1\0\7\22"+
    "\1\0\1\22\3\0\4\22\2\0\11\22\2\0\2\22"+
    "\2\0\4\22\10\0\1\22\4\0\2\22\1\0\5\22"+
    "\2\0\14\22\12\0\1\22\1\0\1\22\2\0\3\22"+
    "\1\0\6\22\4\0\2\22\2\0\26\22\1\0\7\22"+
    "\1\0\2\22\1\0\2\22\1\0\2\22\2\0\1\22"+
    "\1\0\5\22\4\0\2\22\2\0\3\22\3\0\1\22"+
    "\7\0\4\22\1\0\1\22\7\0\20\22\13\0\3\22"+
    "\1\0\11\22\1\0\3\22\1\0\26\22\1\0\7\22"+
    "\1\0\2\22\1\0\5\22\2\0\12\22\1\0\3\22"+
    "\1\0\3\22\2\0\1\22\17\0\4\22\2\0\12\22"+
    "\11\0\7\22\1\0\3\22\1\0\10\22\2\0\2\22"+
    "\2\0\26\22\1\0\7\22\1\0\2\22\1\0\5\22"+
    "\2\0\11\22\2\0\2\22\2\0\3\22\10\0\2\22"+
    "\4\0\2\22\1\0\5\22\2\0\12\22\1\0\1\22"+
    "\20\0\2\22\1\0\6\22\3\0\3\22\1\0\4\22"+
    "\3\0\2\22\1\0\1\22\1\0\2\22\3\0\2\22"+
    "\3\0\3\22\3\0\14\22\4\0\5\22\3\0\3\22"+
    "\1\0\4\22\2\0\1\22\6\0\1\22\16\0\12\22"+
    "\20\0\15\22\1\0\3\22\1\0\27\22\1\0\20\22"+
    "\3\0\10\22\1\0\3\22\1\0\4\22\7\0\2\22"+
    "\1\0\3\22\5\0\4\22\2\0\12\22\20\0\4\22"+
    "\1\0\10\22\1\0\3\22\1\0\27\22\1\0\12\22"+
    "\1\0\5\22\2\0\11\22\1\0\3\22\1\0\4\22"+
    "\7\0\2\22\7\0\1\22\1\0\4\22\2\0\12\22"+
    "\1\0\2\22\15\0\4\22\1\0\10\22\1\0\3\22"+
    "\1\0\63\22\1\0\3\22\1\0\5\22\5\0\4\22"+
    "\7\0\5\22\2\0\12\22\12\0\6\22\2\0\2\22"+
    "\1\0\22\22\3\0\30\22\1\0\11\22\1\0\1\22"+
    "\2\0\7\22\3\0\1\22\4\0\6\22\1\0\1\22"+
    "\1\0\10\22\6\0\12\22\2\0\2\22\15\0\72\22"+
    "\5\0\17\22\1\0\12\22\47\0\2\22\1\0\1\22"+
    "\1\0\5\22\1\0\30\22\1\0\1\22\1\0\27\22"+
    "\2\0\5\22\1\0\1\22\1\0\6\22\2\0\12\22"+
    "\2\0\4\22\40\0\1\22\27\0\2\22\6\0\12\22"+
    "\13\0\1\22\1\0\1\22\1\0\1\22\4\0\12\22"+
    "\1\0\44\22\4\0\24\22\1\0\22\22\1\0\44\22"+
    "\11\0\1\22\71\0\112\22\6\0\116\22\2\0\46\22"+
    "\1\0\1\22\5\0\1\22\2\0\53\22\1\0\115\22"+
    "\1\0\4\22\2\0\7\22\1\0\1\22\1\0\4\22"+
    "\2\0\51\22\1\0\4\22\2\0\41\22\1\0\4\22"+
    "\2\0\7\22\1\0\1\22\1\0\4\22\2\0\17\22"+
    "\1\0\71\22\1\0\4\22\2\0\103\22\2\0\3\22"+
    "\40\0\20\22\20\0\126\22\2\0\6\22\3\0\u016c\22"+
    "\2\0\21\22\1\1\32\22\5\0\113\22\3\0\13\22"+
    "\7\0\15\22\1\0\7\22\13\0\25\22\13\0\24\22"+
    "\14\0\15\22\1\0\3\22\1\0\2\22\14\0\124\22"+
    "\3\0\1\22\4\0\2\22\2\0\12\22\41\0\3\22"+
    "\2\0\12\22\6\0\131\22\7\0\53\22\5\0\106\22"+
    "\12\0\37\22\1\0\14\22\4\0\14\22\12\0\50\22"+
    "\2\0\5\22\13\0\54\22\4\0\32\22\6\0\12\22"+
    "\46\0\34\22\4\0\77\22\1\0\35\22\2\0\13\22"+
    "\6\0\12\22\15\0\1\22\10\0\17\22\101\0\114\22"+
    "\4\0\12\22\21\0\11\22\14\0\164\22\14\0\70\22"+
    "\10\0\12\22\3\0\61\22\2\0\11\22\7\0\53\22"+
    "\2\0\3\22\20\0\3\22\1\0\47\22\5\0\372\22"+
    "\1\0\33\22\2\0\6\22\2\0\46\22\2\0\6\22"+
    "\2\0\10\22\1\0\1\22\1\0\1\22\1\0\1\22"+
    "\1\0\37\22\2\0\65\22\1\0\7\22\1\0\1\22"+
    "\3\0\3\22\1\0\7\22\3\0\4\22\2\0\6\22"+
    "\4\0\15\22\5\0\3\22\1\0\7\22\3\0\13\1"+
    "\35\0\2\3\5\0\1\1\17\0\2\22\23\0\1\22"+
    "\12\0\1\1\21\0\1\22\15\0\1\22\20\0\15\22"+
    "\63\0\41\22\21\0\1\22\4\0\1\22\2\0\12\22"+
    "\1\0\1\22\3\0\5\22\6\0\1\22\1\0\1\22"+
    "\1\0\1\22\1\0\4\22\1\0\13\22\2\0\4\22"+
    "\5\0\5\22\4\0\1\22\21\0\51\22\u022d\0\64\22"+
    "\26\0\57\22\1\0\57\22\1\0\205\22\6\0\11\22"+
    "\14\0\46\22\1\0\1\22\5\0\1\22\2\0\70\22"+
    "\7\0\1\22\17\0\30\22\11\0\7\22\1\0\7\22"+
    "\1\0\7\22\1\0\7\22\1\0\7\22\1\0\7\22"+
    "\1\0\7\22\1\0\7\22\1\0\40\22\57\0\1\22"+
    "\320\0\1\1\4\0\3\22\31\0\17\22\1\0\5\22"+
    "\2\0\5\22\4\0\126\22\2\0\2\22\2\0\3\22"+
    "\1\0\132\22\1\0\4\22\5\0\53\22\1\0\136\22"+
    "\21\0\33\22\65\0\306\22\112\0\360\22\20\0\215\22"+
    "\103\0\56\22\2\0\15\22\3\0\34\22\24\0\63\22"+
    "\1\0\12\22\1\0\163\22\45\0\11\22\2\0\147\22"+
    "\2\0\65\22\2\0\5\22\60\0\61\22\30\0\64\22"+
    "\14\0\106\22\12\0\12\22\6\0\30\22\3\0\1\22"+
    "\1\0\61\22\2\0\44\22\14\0\35\22\3\0\101\22"+
    "\16\0\13\22\6\0\37\22\1\0\67\22\11\0\16\22"+
    "\2\0\12\22\6\0\27\22\3\0\111\22\30\0\3\22"+
    "\2\0\20\22\2\0\5\22\12\0\6\22\2\0\6\22"+
    "\2\0\6\22\11\0\7\22\1\0\7\22\1\0\53\22"+
    "\1\0\14\22\10\0\173\22\1\0\2\22\2\0\12\22"+
    "\6\0\244\22\14\0\27\22\4\0\61\22\4\0\u0100\46"+
    "\156\22\2\0\152\22\46\0\7\22\14\0\5\22\5\0"+
    "\14\22\1\0\15\22\1\0\5\22\1\0\1\22\1\0"+
    "\2\22\1\0\2\22\1\0\154\22\41\0\153\22\22\0"+
    "\100\22\2\0\66\22\50\0\14\22\4\0\20\22\20\0"+
    "\20\22\3\0\2\22\30\0\3\22\40\0\5\22\1\0"+
    "\207\22\23\0\12\22\7\0\32\22\4\0\1\22\1\0"+
    "\32\22\13\0\131\22\3\0\6\22\2\0\6\22\2\0"+
    "\6\22\2\0\3\22\43\0\14\22\1\0\32\22\1\0"+
    "\23\22\1\0\2\22\1\0\17\22\2\0\16\22\42\0"+
    "\173\22\105\0\65\22\210\0\1\22\202\0\35\22\3\0"+
    "\61\22\17\0\1\22\37\0\40\22\15\0\36\22\5\0"+
    "\53\22\5\0\36\22\2\0\44\22\4\0\10\22\1\0"+
    "\5\22\52\0\236\22\2\0\12\22\6\0\44\22\4\0"+
    "\44\22\4\0\50\22\10\0\64\22\234\0\67\22\11\0"+
    "\26\22\12\0\10\22\230\0\6\22\2\0\1\22\1\0"+
    "\54\22\1\0\2\22\3\0\1\22\2\0\27\22\12\0"+
    "\27\22\11\0\37\22\101\0\23\22\1\0\2\22\12\0"+
    "\26\22\12\0\32\22\106\0\70\22\6\0\2\22\100\0"+
    "\4\22\1\0\2\22\5\0\10\22\1\0\3\22\1\0"+
    "\35\22\2\0\3\22\4\0\1\22\40\0\35\22\3\0"+
    "\35\22\43\0\10\22\1\0\36\22\31\0\66\22\12\0"+
    "\26\22\12\0\23\22\15\0\22\22\156\0\111\22\67\0"+
    "\63\22\15\0\63\22\15\0\50\22\10\0\12\22\306\0"+
    "\35\22\12\0\1\22\10\0\41\22\217\0\27\22\11\0"+
    "\107\22\37\0\12\22\17\0\74\22\25\0\31\22\7\0"+
    "\12\22\6\0\65\22\1\0\12\22\4\0\3\22\11\0"+
    "\44\22\2\0\1\22\11\0\105\22\4\0\4\22\3\0"+
    "\13\22\1\0\1\22\43\0\22\22\1\0\45\22\6\0"+
    "\1\22\101\0\7\22\1\0\1\22\1\0\4\22\1\0"+
    "\17\22\1\0\12\22\7\0\73\22\5\0\12\22\6\0"+
    "\4\22\1\0\10\22\2\0\2\22\2\0\26\22\1\0"+
    "\7\22\1\0\2\22\1\0\5\22\1\0\12\22\2\0"+
    "\2\22\2\0\3\22\2\0\1\22\6\0\1\22\5\0"+
    "\7\22\2\0\7\22\3\0\5\22\213\0\113\22\5\0"+
    "\12\22\4\0\2\22\40\0\106\22\1\0\1\22\10\0"+
    "\12\22\246\0\66\22\2\0\11\22\27\0\6\22\42\0"+
    "\101\22\3\0\1\22\13\0\12\22\46\0\71\22\7\0"+
    "\12\22\66\0\33\22\2\0\17\22\4\0\12\22\306\0"+
    "\73\22\145\0\112\22\25\0\1\22\240\0\10\22\2\0"+
    "\56\22\2\0\10\22\1\0\2\22\33\0\77\22\10\0"+
    "\1\22\10\0\112\22\3\0\1\22\42\0\71\22\7\0"+
    "\11\22\1\0\55\22\1\0\11\22\17\0\12\22\30\0"+
    "\36\22\2\0\26\22\1\0\16\22\111\0\7\22\1\0"+
    "\2\22\1\0\54\22\3\0\1\22\1\0\2\22\1\0"+
    "\11\22\10\0\12\22\6\0\6\22\1\0\2\22\1\0"+
    "\45\22\1\0\2\22\1\0\6\22\7\0\12\22\u0136\0"+
    "\27\22\11\0\232\22\146\0\157\22\21\0\304\22\274\0"+
    "\57\22\321\0\107\22\271\0\71\22\7\0\37\22\1\0"+
    "\12\22\146\0\36\22\2\0\5\22\13\0\67\22\11\0"+
    "\4\22\14\0\12\22\11\0\25\22\5\0\23\22\260\0"+
    "\100\22\200\0\113\22\4\0\71\22\7\0\21\22\100\0"+
    "\2\22\1\0\1\22\34\0\370\22\10\0\363\22\15\0"+
    "\37\22\61\0\3\22\21\0\4\22\10\0\u018c\22\4\0"+
    "\153\22\5\0\15\22\3\0\11\22\7\0\12\22\3\0"+
    "\2\22\306\0\5\22\3\0\6\22\10\0\10\22\2\0"+
    "\7\22\36\0\4\22\224\0\3\22\273\0\125\22\1\0"+
    "\107\22\1\0\2\22\2\0\1\22\2\0\2\22\2\0"+
    "\4\22\1\0\14\22\1\0\1\22\1\0\7\22\1\0"+
    "\101\22\1\0\4\22\2\0\10\22\1\0\7\22\1\0"+
    "\34\22\1\0\4\22\1\0\5\22\1\0\1\22\3\0"+
    "\7\22\1\0\u0154\22\2\0\31\22\1\0\31\22\1\0"+
    "\37\22\1\0\31\22\1\0\37\22\1\0\31\22\1\0"+
    "\37\22\1\0\31\22\1\0\37\22\1\0\31\22\1\0"+
    "\10\22\2\0\151\22\4\0\62\22\10\0\1\22\16\0"+
    "\1\22\26\0\5\22\1\0\17\22\120\0\7\22\1\0"+
    "\21\22\2\0\7\22\1\0\2\22\1\0\5\22\325\0"+
    "\55\22\3\0\16\22\2\0\12\22\4\0\1\22\u0171\0"+
    "\72\22\6\0\305\22\13\0\7\22\51\0\114\22\4\0"+
    "\12\22\246\0\4\22\1\0\33\22\1\0\2\22\1\0"+
    "\1\22\2\0\1\22\1\0\12\22\1\0\4\22\1\0"+
    "\1\22\1\0\1\22\6\0\1\22\4\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\3\22\1\0\2\22\1\0"+
    "\1\22\2\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\2\22\1\0\1\22\2\0"+
    "\4\22\1\0\7\22\1\0\4\22\1\0\4\22\1\0"+
    "\1\22\1\0\12\22\1\0\21\22\5\0\3\22\1\0"+
    "\5\22\1\0\21\22\164\0\32\22\6\0\32\22\6\0"+
    "\32\22\166\0\327\22\51\0\65\22\13\0\336\22\2\0"+
    "\u0182\22\16\0\u0131\22\37\0\36\22\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\2\1\1\4\1\5"+
    "\1\6\1\1\1\7\1\10\7\1\1\11\1\12\1\13"+
    "\1\0\1\14\1\0\1\3\1\15\3\0\1\16\6\0"+
    "\1\17\7\0\1\20\1\7\1\20\7\0\1\7\2\0"+
    "\1\7\11\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\47\0\47\0\47\0\u0138\0\u015f\0\47\0\u0186\0\u01ad"+
    "\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\47\0\47\0\165"+
    "\0\234\0\47\0\u0297\0\47\0\352\0\u0111\0\u02be\0\u0138"+
    "\0\47\0\u01ad\0\u01d4\0\u02e5\0\u030c\0\u0333\0\u035a\0\u0186"+
    "\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b\0\u01ad"+
    "\0\u0492\0\47\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c"+
    "\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u05a3\0\u063f\0\u0666\0\u068d"+
    "\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\2\1\13\1\14\1\15\1\2\1\16\1\17"+
    "\2\20\1\21\1\20\1\22\3\20\1\23\6\20\1\24"+
    "\1\20\1\25\1\26\1\27\1\2\50\0\3\3\60\0"+
    "\3\30\2\0\2\30\1\0\17\30\3\0\5\31\1\32"+
    "\16\31\1\33\22\31\2\6\1\0\1\34\42\6\1\34"+
    "\15\0\2\35\3\0\2\35\1\0\17\35\3\0\10\36"+
    "\1\32\13\36\1\37\22\36\15\0\2\40\1\41\2\0"+
    "\2\42\1\43\1\42\1\44\6\42\1\45\1\46\5\42"+
    "\20\0\1\47\1\15\1\41\2\0\2\42\1\43\1\42"+
    "\1\44\6\42\1\45\1\46\5\42\20\0\2\50\3\0"+
    "\2\50\1\0\17\50\20\0\2\42\1\41\2\0\2\42"+
    "\1\0\17\42\20\0\2\43\5\0\1\43\1\0\1\51"+
    "\6\0\1\52\1\53\25\0\2\42\1\41\2\0\2\42"+
    "\1\0\13\42\1\54\3\42\20\0\2\42\1\41\2\0"+
    "\2\42\1\0\1\42\1\55\15\42\20\0\2\42\1\41"+
    "\2\0\2\42\1\0\11\42\1\56\5\42\20\0\2\42"+
    "\1\41\2\0\2\42\1\0\3\42\1\57\13\42\3\0"+
    "\2\31\2\0\42\31\1\0\2\36\2\0\42\36\16\0"+
    "\2\42\1\41\2\0\2\42\1\0\10\42\1\60\6\42"+
    "\20\0\2\42\1\41\2\0\2\42\1\0\15\42\1\60"+
    "\1\42\20\0\2\42\1\41\2\0\2\42\1\0\4\42"+
    "\1\60\7\42\1\60\2\42\20\0\1\40\1\61\1\41"+
    "\2\0\2\42\1\43\1\42\1\44\6\42\1\45\1\46"+
    "\5\42\40\0\1\62\53\0\1\62\35\0\1\62\7\0"+
    "\1\62\22\0\2\42\1\41\2\0\2\42\1\0\12\42"+
    "\1\63\4\42\20\0\2\42\1\41\2\0\2\42\1\0"+
    "\12\42\1\64\4\42\20\0\2\42\1\41\2\0\2\42"+
    "\1\0\1\42\1\65\15\42\20\0\2\42\1\41\2\0"+
    "\2\42\1\0\11\42\1\63\5\42\20\0\1\40\1\61"+
    "\1\41\2\0\1\42\1\66\1\43\1\42\1\44\1\42"+
    "\1\66\4\42\1\45\1\46\5\42\20\0\2\42\1\41"+
    "\2\0\2\42\1\0\7\42\1\60\7\42\20\0\2\42"+
    "\1\41\2\0\2\42\1\0\2\42\1\67\14\42\20\0"+
    "\2\42\1\41\2\0\2\42\1\0\10\42\1\70\6\42"+
    "\16\0\1\71\1\0\1\42\1\72\1\41\2\0\2\42"+
    "\1\0\17\42\20\0\2\42\1\41\2\0\2\42\1\0"+
    "\4\42\1\73\12\42\20\0\2\42\1\41\2\0\2\42"+
    "\1\0\1\74\16\42\21\0\1\75\45\0\1\42\1\72"+
    "\1\41\2\0\2\42\1\0\17\42\20\0\2\42\1\41"+
    "\2\0\2\42\1\0\1\76\16\42\20\0\2\42\1\41"+
    "\2\0\2\42\1\0\2\42\1\77\14\42\20\0\2\42"+
    "\1\41\2\0\2\42\1\0\10\42\1\100\6\42\20\0"+
    "\2\42\1\41\2\0\2\42\1\0\7\42\1\101\7\42"+
    "\20\0\2\42\1\41\2\0\2\42\1\0\1\42\1\102"+
    "\15\42\20\0\2\42\1\41\2\0\2\42\1\0\6\42"+
    "\1\103\10\42\20\0\2\42\1\41\2\0\2\42\1\0"+
    "\11\42\1\104\5\42\20\0\2\42\1\41\2\0\2\42"+
    "\1\0\12\42\1\104\4\42\20\0\2\42\1\41\2\0"+
    "\2\42\1\0\3\42\1\105\13\42\20\0\2\42\1\41"+
    "\2\0\2\42\1\0\6\42\1\106\10\42\20\0\2\42"+
    "\1\41\2\0\2\42\1\0\12\42\1\60\4\42\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1950];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\3\11\2\1\1\11\7\1\2\11"+
    "\1\1\1\0\1\11\1\0\1\11\1\1\3\0\1\11"+
    "\6\0\1\1\7\0\2\1\1\11\7\0\1\1\2\0"+
    "\1\1\11\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PuiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 17: break;
          case 2:
            { return TokenType.WHITE_SPACE;
            }
          // fall through
          case 18: break;
          case 3:
            { return PuiTypes.COMMENT;
            }
          // fall through
          case 19: break;
          case 4:
            { return PuiTypes.OPEN_BRACE;
            }
          // fall through
          case 20: break;
          case 5:
            { return PuiTypes.CLOSE_BRACE;
            }
          // fall through
          case 21: break;
          case 6:
            { return PuiTypes.COMMA;
            }
          // fall through
          case 22: break;
          case 7:
            { return PuiTypes.NUMBER;
            }
          // fall through
          case 23: break;
          case 8:
            { return PuiTypes.ASSIGN;
            }
          // fall through
          case 24: break;
          case 9:
            { return PuiTypes.OPEN_BRACKET;
            }
          // fall through
          case 25: break;
          case 10:
            { return PuiTypes.CLOSE_BRACKET;
            }
          // fall through
          case 26: break;
          case 11:
            { return PuiTypes.RESOURCE;
            }
          // fall through
          case 27: break;
          case 12:
            { return PuiTypes.LITERAL;
            }
          // fall through
          case 28: break;
          case 13:
            { return PuiTypes.ALIAS;
            }
          // fall through
          case 29: break;
          case 14:
            { return PuiTypes.KEY;
            }
          // fall through
          case 30: break;
          case 15:
            { return PuiTypes.COMPONENT;
            }
          // fall through
          case 31: break;
          case 16:
            { return PuiTypes.CONSTRAINT;
            }
          // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
