{
  parserClass="online.generalpashon.jpizeuihighlighter.parser.PuiParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Pui"
  psiImplClassSuffix="Impl"
  psiPackage="online.generalpashon.jpizeuihighlighter.parser.psi"
  psiImplPackage="online.generalpashon.jpizeuihighlighter.parser.impl"

  elementTypeHolderClass="online.generalpashon.jpizeuihighlighter.lexer.PuiTypes"
  elementTypeClass="online.generalpashon.jpizeuihighlighter.lexer.PuiElementType"
  tokenTypeClass="online.generalpashon.jpizeuihighlighter.parser.PuiTokenType"
}

pui_file ::= (alias_block|COMMENT)* component_block

component_block ::= COMPONENT arguments? OPEN_BRACKET (component_block|field|COMMENT)* CLOSE_BRACKET
arguments ::= vector

alias_block ::= ALIAS ASSIGN value

field ::= KEY value
value ::= vector|group|single_value

single_value ::= NUMBER|CONSTRAINT|LITERAL|RESOURCE|ALIAS
vector ::= OPEN_BRACE (single_value COMMA?)* CLOSE_BRACE
group ::= OPEN_BRACKET (field|COMMENT)* CLOSE_BRACKET


